# Generated by Django 5.1.1 on 2024-10-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_makanan_id'),
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='foods',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='food',
            field=models.ManyToManyField(related_name='wishlists', to='main.makanan'),
        ),
        migrations.DeleteModel(
            name='Food',
        ),
    ]
