# Generated by Django 5.1.1 on 2024-12-15 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='food',
        ),
    ]
