# Generated by Django 5.1.1 on 2024-12-19 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_artikel'),
        ('wishlist', '0003_wishlist_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='food',
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.makanan')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wishlist.wishlist')),
            ],
            options={
                'unique_together': {('wishlist', 'food')},
            },
        ),
    ]
