# Generated by Django 5.1.2 on 2024-10-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('konten', models.TextField()),
                ('tanggal_publikasi', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-tanggal_publikasi'],
            },
        ),
        migrations.CreateModel(
            name='Makanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('kategori', models.CharField(max_length=100)),
                ('restoran', models.CharField(max_length=255)),
                ('harga', models.DecimalField(decimal_places=0, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('gambar', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['nama'],
            },
        ),
    ]
