# Generated by Django 4.2.1 on 2024-10-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_makanan_harga_alter_makanan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makanan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
