# Generated by Django 5.1.2 on 2024-10-19 08:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_makanan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makanan',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
