# Generated by Django 5.1.2 on 2024-10-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_makanan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makanan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
