# Generated by Django 5.1.2 on 2024-12-09 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_makanan_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artikel',
        ),
    ]
