# Generated by Django 5.1.1 on 2024-10-27 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_food_rating'),
        ('details', '0002_alter_review_food_alter_review_food_alt'),
        ('main', '0005_alter_makanan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.makanan'),
        ),
        migrations.AlterField(
            model_name='review',
            name='food_alt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.food'),
        ),
    ]
